ALTER TABLE index_stats
ADD COLUMN IF NOT EXISTS ndvi_anomaly DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS ndwi_anomaly DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS lst_anomaly_c DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS ndvi_severity TEXT,
ADD COLUMN IF NOT EXISTS ndwi_severity TEXT,
ADD COLUMN IF NOT EXISTS lst_severity TEXT;
